wandb_version: 1

clf_name:
  desc: null
  value: LGBMClassifier
reg_name:
  desc: null
  value: LGBMRegressor
transform:
  desc: null
  value: log
level:
  desc: null
  value: cm
run_id:
  desc: null
  value: Fatalities003
steps:
  desc: null
  value:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  - 18
  - 19
  - 20
  - 21
  - 22
  - 23
  - 24
  - 25
  - 26
  - 27
  - 28
  - 29
  - 30
  - 31
  - 32
  - 33
  - 34
  - 35
  - 36
calib_partitioner_dict:
  desc: null
  value:
    train:
    - 121
    - 396
    predict:
    - 397
    - 444
test_partitioner_dict:
  desc: null
  value:
    train:
    - 121
    - 444
    predict:
    - 445
    - 492
future_partitioner_dict:
  desc: null
  value:
    train:
    - 121
    - 492
    predict:
    - 493
    - 504
FutureStart:
  desc: null
  value: 508
get_future:
  desc: null
  value: false
force_retrain:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.0
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1702393290.559495
    t:
      1:
      - 5
      - 6
      - 8
      - 53
      - 54
      - 55
      2:
      - 5
      - 6
      - 8
      - 53
      - 54
      - 55
      3:
      - 2
      - 16
      - 17
      - 23
      - 37
      4: 3.9.18
      5: 0.16.0
      8:
      - 4
      - 5
      13: darwin-arm64
modelname:
  desc: null
  value: fatalities003_nl_conflicthistory_nonlog_hurdle_lgb
algorithm:
  desc: null
  value: HurdleRegression
depvar:
  desc: null
  value: ged_sb_dep
data_train:
  desc: null
  value: conflict_nonlog
queryset:
  desc: null
  value: fatalities003_conflict_history_nonlog
preprocessing:
  desc: null
  value: float_it
description:
  desc: null
  value: A collection of variables that together map the conflict history of a country,
    random forests regression model.
long_description:
  desc: null
  value: A collection of variables that together map the conflict history of a country.
    The features include lagged dependent variables for each conflict type as coded
    by the UCDP (state-based, one-sided, or non-state) for up to each of the preceding
    six months, decay functions of time since conflict caused 5, 100, and 500 deaths
    in a month, for each type of violence, whether ACLED (https://doi.org/10.1177/0022343310378914
    recorded similar violence, and whether there was recent violence in any neighboring
    countries.
